### ISSUE TITLE
How to provide intents to discord.js 13?

### ISSUE THREAD

**Issue by Maks1116** [Garlic-Team/GCommands#142]
Discord.js 13 requires providing intents, but is there way to provide it in GCommandsClient?
```
D:\Programowanie\Projekty\DiscordBackup\node_modules\discord.js\src\client\Client.js:544
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at GCommandsClient._validateOptions (D:\Programowanie\Projekty\DiscordBackup\node_modules\discord.js\src\client\Client.js:544:13)
    at new Client (D:\Programowanie\Projekty\DiscordBackup\node_modules\discord.js\src\client\Client.js:73:10)
    at new GCommandsClient (D:\Programowanie\Projekty\DiscordBackup\node_modules\gcommands\src\base\GCommandsClient.js:23:9)
    at Object.<anonymous> (D:\Programowanie\Projekty\DiscordBackup\index.js:3:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}
```

**Comment by S222em** [comment]
Just pas the intents option in the GCommandsClient
```javascript
new GCommandsClient({
   intents: [all your intents],
});
```

**Comment by xHyroM** [comment]
You can put discord.js client options in GCommandsClient, but you can also put GCommands options in GCommandsClient. So you just add `intents:[etc]`.

Next time we will be glad if you prefer to go to our discord server [Garlic Team](https://discord.gg/garlic) for questions.

**Comment by anondev-sudo** [comment]
How to provide all intents without providing them all manually

**Comment by S222em** [comment]
```js
intents: Object.keys(Intents.FLAGS)
```

**Comment by xHyroM** [comment]
> 
> 
> How to provide all intents without providing them all manually

It's bullshit, intents are just to keep the bot from eating your ram unnecessarily.

**Comment by Maks1116** [comment]
> > How to provide all intents without providing them all manually
> 
> It's bullshit, intents are just to keep the bot from eating your ram unnecessarily.
For some smaller bots this doesn't make difference
